DROP TABLE IF EXISTS in_role CASCADE;

DROP TABLE IF EXISTS in_user CASCADE;

DROP TABLE IF EXISTS in_category CASCADE;

DROP TABLE IF EXISTS in_product CASCADE;

DROP TABLE IF EXISTS in_size CASCADE;

DROP TABLE IF EXISTS in_quantity CASCADE;

DROP TABLE IF EXISTS in_products_sizes CASCADE;

DROP TABLE IF EXISTS in_sizes_quantities CASCADE;
